/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CotizarRouteImport } from './routes/cotizar'
import { Route as HomeRouteImport } from './routes/home'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as HomeIndexRouteImport } from './routes/home.index'
import { Route as HomeContactoRouteImport } from './routes/home.contacto'
import { Route as HomeNosotrosRouteImport } from './routes/home.nosotros'
import { Route as HomeProduccionRouteImport } from './routes/home.produccion'
import { Route as HomeProyectosRouteImport } from './routes/home.proyectos'
import { Route as ProyectosIndexRouteImport } from './routes/proyectos.index'
import { Route as ProyectosSlugRouteImport } from './routes/proyectos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizarRoute = CotizarRouteImport.update({
  id: '/cotizar',
  path: '/cotizar',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const HomeContactoRoute = HomeContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => HomeRoute,
} as any)
const HomeNosotrosRoute = HomeNosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => HomeRoute,
} as any)
const HomeProduccionRoute = HomeProduccionRouteImport.update({
  id: '/produccion',
  path: '/produccion',
  getParentRoute: () => HomeRoute,
} as any)
const HomeProyectosRoute = HomeProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => HomeRoute,
} as any)
const ProyectosIndexRoute = ProyectosIndexRouteImport.update({
  id: '/proyectos/',
  path: '/proyectos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosSlugRoute = ProyectosSlugRouteImport.update({
  id: '/proyectos/$slug',
  path: '/proyectos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cotizar': typeof CotizarRoute
  '/home': typeof HomeRouteWithChildren
  '/nosotros': typeof NosotrosRoute
  '/servicios': typeof ServiciosRoute
  '/home/contacto': typeof HomeContactoRoute
  '/home/nosotros': typeof HomeNosotrosRoute
  '/home/produccion': typeof HomeProduccionRoute
  '/home/proyectos': typeof HomeProyectosRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
  '/home/': typeof HomeIndexRoute
  '/proyectos/': typeof ProyectosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cotizar': typeof CotizarRoute
  '/nosotros': typeof NosotrosRoute
  '/servicios': typeof ServiciosRoute
  '/home/contacto': typeof HomeContactoRoute
  '/home/nosotros': typeof HomeNosotrosRoute
  '/home/produccion': typeof HomeProduccionRoute
  '/home/proyectos': typeof HomeProyectosRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
  '/home': typeof HomeIndexRoute
  '/proyectos': typeof ProyectosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cotizar': typeof CotizarRoute
  '/home': typeof HomeRouteWithChildren
  '/nosotros': typeof NosotrosRoute
  '/servicios': typeof ServiciosRoute
  '/home/contacto': typeof HomeContactoRoute
  '/home/nosotros': typeof HomeNosotrosRoute
  '/home/produccion': typeof HomeProduccionRoute
  '/home/proyectos': typeof HomeProyectosRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
  '/home/': typeof HomeIndexRoute
  '/proyectos/': typeof ProyectosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cotizar'
    | '/home'
    | '/nosotros'
    | '/servicios'
    | '/home/contacto'
    | '/home/nosotros'
    | '/home/produccion'
    | '/home/proyectos'
    | '/proyectos/$slug'
    | '/home/'
    | '/proyectos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cotizar'
    | '/nosotros'
    | '/servicios'
    | '/home/contacto'
    | '/home/nosotros'
    | '/home/produccion'
    | '/home/proyectos'
    | '/proyectos/$slug'
    | '/home'
    | '/proyectos'
  id:
    | '__root__'
    | '/'
    | '/cotizar'
    | '/home'
    | '/nosotros'
    | '/servicios'
    | '/home/contacto'
    | '/home/nosotros'
    | '/home/produccion'
    | '/home/proyectos'
    | '/proyectos/$slug'
    | '/home/'
    | '/proyectos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CotizarRoute: typeof CotizarRoute
  HomeRoute: typeof HomeRouteWithChildren
  NosotrosRoute: typeof NosotrosRoute
  ServiciosRoute: typeof ServiciosRoute
  ProyectosSlugRoute: typeof ProyectosSlugRoute
  ProyectosIndexRoute: typeof ProyectosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizar': {
      id: '/cotizar'
      path: '/cotizar'
      fullPath: '/cotizar'
      preLoaderRoute: typeof CotizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/contacto': {
      id: '/home/contacto'
      path: '/contacto'
      fullPath: '/home/contacto'
      preLoaderRoute: typeof HomeContactoRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/nosotros': {
      id: '/home/nosotros'
      path: '/nosotros'
      fullPath: '/home/nosotros'
      preLoaderRoute: typeof HomeNosotrosRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/produccion': {
      id: '/home/produccion'
      path: '/produccion'
      fullPath: '/home/produccion'
      preLoaderRoute: typeof HomeProduccionRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/proyectos': {
      id: '/home/proyectos'
      path: '/proyectos'
      fullPath: '/home/proyectos'
      preLoaderRoute: typeof HomeProyectosRouteImport
      parentRoute: typeof HomeRoute
    }
    '/proyectos/': {
      id: '/proyectos/'
      path: '/proyectos'
      fullPath: '/proyectos/'
      preLoaderRoute: typeof ProyectosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/$slug': {
      id: '/proyectos/$slug'
      path: '/proyectos/$slug'
      fullPath: '/proyectos/$slug'
      preLoaderRoute: typeof ProyectosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HomeRouteChildren {
  HomeContactoRoute: typeof HomeContactoRoute
  HomeNosotrosRoute: typeof HomeNosotrosRoute
  HomeProduccionRoute: typeof HomeProduccionRoute
  HomeProyectosRoute: typeof HomeProyectosRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeContactoRoute: HomeContactoRoute,
  HomeNosotrosRoute: HomeNosotrosRoute,
  HomeProduccionRoute: HomeProduccionRoute,
  HomeProyectosRoute: HomeProyectosRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CotizarRoute: CotizarRoute,
  HomeRoute: HomeRouteWithChildren,
  NosotrosRoute: NosotrosRoute,
  ServiciosRoute: ServiciosRoute,
  ProyectosSlugRoute: ProyectosSlugRoute,
  ProyectosIndexRoute: ProyectosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
