/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitioRouteImport } from './routes/_sitio'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as SitioIndexRouteImport } from './routes/_sitio.index'
import { Route as SitioContactoRouteImport } from './routes/_sitio.contacto'
import { Route as SitioNosotrosRouteImport } from './routes/_sitio.nosotros'
import { Route as SitioProduccionRouteImport } from './routes/_sitio.produccion'
import { Route as SitioProyectosRouteImport } from './routes/_sitio.proyectos'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DemoCotizarRouteImport } from './routes/demo.cotizar'
import { Route as DemoNosotrosRouteImport } from './routes/demo.nosotros'
import { Route as DemoServiciosRouteImport } from './routes/demo.servicios'
import { Route as HomeIndexRouteImport } from './routes/home.index'
import { Route as HomeSplatRouteImport } from './routes/home.$'
import { Route as DemoProyectosIndexRouteImport } from './routes/demo.proyectos.index'
import { Route as DemoProyectosSlugRouteImport } from './routes/demo.proyectos.$slug'

const SitioRoute = SitioRouteImport.update({
  id: '/_sitio',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const SitioIndexRoute = SitioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SitioRoute,
} as any)
const SitioContactoRoute = SitioContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => SitioRoute,
} as any)
const SitioNosotrosRoute = SitioNosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => SitioRoute,
} as any)
const SitioProduccionRoute = SitioProduccionRouteImport.update({
  id: '/produccion',
  path: '/produccion',
  getParentRoute: () => SitioRoute,
} as any)
const SitioProyectosRoute = SitioProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => SitioRoute,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoCotizarRoute = DemoCotizarRouteImport.update({
  id: '/cotizar',
  path: '/cotizar',
  getParentRoute: () => DemoRoute,
} as any)
const DemoNosotrosRoute = DemoNosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => DemoRoute,
} as any)
const DemoServiciosRoute = DemoServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => DemoRoute,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeSplatRoute = HomeSplatRouteImport.update({
  id: '/home/$',
  path: '/home/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoProyectosIndexRoute = DemoProyectosIndexRouteImport.update({
  id: '/proyectos/',
  path: '/proyectos/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoProyectosSlugRoute = DemoProyectosSlugRouteImport.update({
  id: '/proyectos/$slug',
  path: '/proyectos/$slug',
  getParentRoute: () => DemoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SitioIndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/contacto': typeof SitioContactoRoute
  '/nosotros': typeof SitioNosotrosRoute
  '/produccion': typeof SitioProduccionRoute
  '/proyectos': typeof SitioProyectosRoute
  '/demo/cotizar': typeof DemoCotizarRoute
  '/demo/nosotros': typeof DemoNosotrosRoute
  '/demo/servicios': typeof DemoServiciosRoute
  '/home/$': typeof HomeSplatRoute
  '/demo/': typeof DemoIndexRoute
  '/home/': typeof HomeIndexRoute
  '/demo/proyectos/$slug': typeof DemoProyectosSlugRoute
  '/demo/proyectos/': typeof DemoProyectosIndexRoute
}
export interface FileRoutesByTo {
  '/contacto': typeof SitioContactoRoute
  '/nosotros': typeof SitioNosotrosRoute
  '/produccion': typeof SitioProduccionRoute
  '/proyectos': typeof SitioProyectosRoute
  '/demo/cotizar': typeof DemoCotizarRoute
  '/demo/nosotros': typeof DemoNosotrosRoute
  '/demo/servicios': typeof DemoServiciosRoute
  '/home/$': typeof HomeSplatRoute
  '/': typeof SitioIndexRoute
  '/demo': typeof DemoIndexRoute
  '/home': typeof HomeIndexRoute
  '/demo/proyectos/$slug': typeof DemoProyectosSlugRoute
  '/demo/proyectos': typeof DemoProyectosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_sitio': typeof SitioRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/_sitio/contacto': typeof SitioContactoRoute
  '/_sitio/nosotros': typeof SitioNosotrosRoute
  '/_sitio/produccion': typeof SitioProduccionRoute
  '/_sitio/proyectos': typeof SitioProyectosRoute
  '/demo/cotizar': typeof DemoCotizarRoute
  '/demo/nosotros': typeof DemoNosotrosRoute
  '/demo/servicios': typeof DemoServiciosRoute
  '/home/$': typeof HomeSplatRoute
  '/_sitio/': typeof SitioIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/home/': typeof HomeIndexRoute
  '/demo/proyectos/$slug': typeof DemoProyectosSlugRoute
  '/demo/proyectos/': typeof DemoProyectosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/contacto'
    | '/nosotros'
    | '/produccion'
    | '/proyectos'
    | '/demo/cotizar'
    | '/demo/nosotros'
    | '/demo/servicios'
    | '/home/$'
    | '/demo/'
    | '/home/'
    | '/demo/proyectos/$slug'
    | '/demo/proyectos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/contacto'
    | '/nosotros'
    | '/produccion'
    | '/proyectos'
    | '/demo/cotizar'
    | '/demo/nosotros'
    | '/demo/servicios'
    | '/home/$'
    | '/'
    | '/demo'
    | '/home'
    | '/demo/proyectos/$slug'
    | '/demo/proyectos'
  id:
    | '__root__'
    | '/_sitio'
    | '/demo'
    | '/_sitio/contacto'
    | '/_sitio/nosotros'
    | '/_sitio/produccion'
    | '/_sitio/proyectos'
    | '/demo/cotizar'
    | '/demo/nosotros'
    | '/demo/servicios'
    | '/home/$'
    | '/_sitio/'
    | '/demo/'
    | '/home/'
    | '/demo/proyectos/$slug'
    | '/demo/proyectos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SitioRoute: typeof SitioRouteWithChildren
  DemoRoute: typeof DemoRouteWithChildren
  HomeSplatRoute: typeof HomeSplatRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sitio': {
      id: '/_sitio'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SitioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sitio/': {
      id: '/_sitio/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SitioIndexRouteImport
      parentRoute: typeof SitioRoute
    }
    '/_sitio/contacto': {
      id: '/_sitio/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof SitioContactoRouteImport
      parentRoute: typeof SitioRoute
    }
    '/_sitio/nosotros': {
      id: '/_sitio/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof SitioNosotrosRouteImport
      parentRoute: typeof SitioRoute
    }
    '/_sitio/produccion': {
      id: '/_sitio/produccion'
      path: '/produccion'
      fullPath: '/produccion'
      preLoaderRoute: typeof SitioProduccionRouteImport
      parentRoute: typeof SitioRoute
    }
    '/_sitio/proyectos': {
      id: '/_sitio/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof SitioProyectosRouteImport
      parentRoute: typeof SitioRoute
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/cotizar': {
      id: '/demo/cotizar'
      path: '/cotizar'
      fullPath: '/demo/cotizar'
      preLoaderRoute: typeof DemoCotizarRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/nosotros': {
      id: '/demo/nosotros'
      path: '/nosotros'
      fullPath: '/demo/nosotros'
      preLoaderRoute: typeof DemoNosotrosRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/servicios': {
      id: '/demo/servicios'
      path: '/servicios'
      fullPath: '/demo/servicios'
      preLoaderRoute: typeof DemoServiciosRouteImport
      parentRoute: typeof DemoRoute
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/$': {
      id: '/home/$'
      path: '/home/$'
      fullPath: '/home/$'
      preLoaderRoute: typeof HomeSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/proyectos/': {
      id: '/demo/proyectos/'
      path: '/proyectos'
      fullPath: '/demo/proyectos/'
      preLoaderRoute: typeof DemoProyectosIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/proyectos/$slug': {
      id: '/demo/proyectos/$slug'
      path: '/proyectos/$slug'
      fullPath: '/demo/proyectos/$slug'
      preLoaderRoute: typeof DemoProyectosSlugRouteImport
      parentRoute: typeof DemoRoute
    }
  }
}

interface SitioRouteChildren {
  SitioContactoRoute: typeof SitioContactoRoute
  SitioNosotrosRoute: typeof SitioNosotrosRoute
  SitioProduccionRoute: typeof SitioProduccionRoute
  SitioProyectosRoute: typeof SitioProyectosRoute
  SitioIndexRoute: typeof SitioIndexRoute
}

const SitioRouteChildren: SitioRouteChildren = {
  SitioContactoRoute: SitioContactoRoute,
  SitioNosotrosRoute: SitioNosotrosRoute,
  SitioProduccionRoute: SitioProduccionRoute,
  SitioProyectosRoute: SitioProyectosRoute,
  SitioIndexRoute: SitioIndexRoute,
}

const SitioRouteWithChildren = SitioRoute._addFileChildren(SitioRouteChildren)

interface DemoRouteChildren {
  DemoCotizarRoute: typeof DemoCotizarRoute
  DemoNosotrosRoute: typeof DemoNosotrosRoute
  DemoServiciosRoute: typeof DemoServiciosRoute
  DemoIndexRoute: typeof DemoIndexRoute
  DemoProyectosSlugRoute: typeof DemoProyectosSlugRoute
  DemoProyectosIndexRoute: typeof DemoProyectosIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoCotizarRoute: DemoCotizarRoute,
  DemoNosotrosRoute: DemoNosotrosRoute,
  DemoServiciosRoute: DemoServiciosRoute,
  DemoIndexRoute: DemoIndexRoute,
  DemoProyectosSlugRoute: DemoProyectosSlugRoute,
  DemoProyectosIndexRoute: DemoProyectosIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SitioRoute: SitioRouteWithChildren,
  DemoRoute: DemoRouteWithChildren,
  HomeSplatRoute: HomeSplatRoute,
  HomeIndexRoute: HomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
